### ISSUE TITLE
Need help for pcb

### ISSUE THREAD

**Issue by 4dvn** [203Industries/Matrix#1]
@203Null  can you upload the image of pcb file, the QQ chat i can't join because the phone number is locked in my country, i need some tutorial to flash the bootloader and code, thank you!

**Comment by 203Null** [comment]
Sure but https://github.com/203Industries/Matrix-Hardware might be a better place for this. 
Do you have a discord?

Sorry for the lack of localization. I didn't do translate and some other localization yet because I don't think the project is ready at the moment.

**Comment by 4dvn** [comment]
Thank you for reply, here is my discord link: https://discord.gg/sQTDTHD
